apiVersion: v1
kind: Service
metadata:
  name:  keerthi-rtp-service
  namespace: keerthi
spec:
  type: NodePort
  selector:
    app: keerthi-rtp
  ports:
  - nodePort: 30082
    port: 8000
    targetPort: 8000
